export { default as Ink } from "./Ink";
export { default as Copy } from "./Copy";
export { default as Delete } from "./Delete";
export { default as Filter } from "./Filter";
export { default as Google } from "./Google";
export { default as Master } from "./Master";
export { default as Search } from "./Search";
export { default as TickMark } from "./TickMark";
export { default as Visa } from "./Visa";
